### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by SpargelPlays** [KCreate/charly-lang#30]
| Operator | Usage |
| --- | --- |
| Bitwise AND | a & b |
| Bitwise OR | a | b |
| Bitwise XOR | a ^ b |
| Bitwise NOT | ~ a |
| Left shift | a << b |
| Sign-propagating right shift | a >> b |
| Zero-fill right shift | a >>> b |

**Comment by KCreate** [comment]
Charly uses the [`Float64`](https://crystal-lang.org/api/master/Float64.html) type from crystal to represent the Numeric type.

Doing bitwise operations on a floating-point number would work, it just results in complete garbage and is (probably?) useless.

See [https://gist.github.com/JadenGeller/aa37541962493138fcc4](https://gist.github.com/JadenGeller/aa37541962493138fcc4)

**Comment by KCreate** [comment]
This is being worked on on the `bitwise-operators` branch
